apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: REPLACE_IMAGE_URI
        ports:
        - containerPort: 80
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: aws-auth
    namespace: kube-system
  data:
    mapRoles: |
      - rolearn: arn:aws:iam::119739005737:user/aulaaplicacaoemnuvem
        username: aulaaplicacaoemnuvem
        groups:
          - system:masters
    mapUsers: |
      - userarn: arn:aws:iam::119739005737:user/<USER_NAME>
        username: aulaaplicacaoemnuvem
        groups:
          - system:masters        