---
apiVersion: v1
kind: Namespace
metadata:
  name: backendchallenge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendchallenge-deployment
  namespace: backendchallenge
  labels:
    app: backendchallenge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backendchallenge-app
  template:
    metadata:
      labels:
        app: backendchallenge-app
    spec:
      containers:
      - name: backendchallenge-container
        image: REPLACE_IMAGE_URI
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backendchallengeservice
  namespace: backendchallenge
  labels:
    app: backendchallenge-app
spec:
  type: LoadBalancer # Pode ser ClusterIP, NodePort ou LoadBalancer
  selector:
    app: backendchallenge-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80