name: CI/CD Pipeline

on:
  push:
    branches: [ feature/* ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Listar arquivos no diretório atual
      run: |
        ls -la

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        pip install -r /fastapi-hello-world/requirements.txt

    - name: Executar testes
      run: |
        pytest