name: CI/CD Pipeline

on:
  push:
    branches: [ feature/* ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Exibir diretório atual
      run: pwd

    - name: Limpar arquivos de cache Python
      run: |
        find . -name "*.pyc" -delete
        find . -type d -name "__pycache__" -exec rm -r {} +

    - name: Executar testes
      working-directory: ./fastapi-hello-world
      run: |
        pytest

    - name: Executar testes
      run: |
        pytest || exit_code=$?
        if [ "$exit_code" -eq 5 ]; then
          echo "Nenhum teste encontrado. Continuando..."
          exit 0
        else
          exit $exit_code
        fi